plugins {
    id 'java'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
    compileJava.options.encoding('UTF-8')
}

group = 'com.github.romanqed.di.examples'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'io.github.amayaframework', name: 'amaya-di', version: '3.0.4'
    implementation group: 'io.github.amayaframework', name: 'amaya-di-reflect', version: '2.0.0'
    implementation group: 'io.github.amayaframework', name: 'amaya-di-asm', version: '2.0.2'
}
